# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the nebula branch
  push:
    branches: [ nebula ]
  pull_request:
    branches: [ nebula ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml up -d

      - name: Install sshpass package
        run: sudo apt-get install sshpass

      - name: Install sshpass package
        run: sshpass -p "nebula" ./run_cmd.sh echo "hello"
