# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the nebula branch
  push:
    branches: [ nebula ]
  pull_request:
    branches: [ nebula ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml up -d

      - name: Install sshpass package
        run: sudo apt-get install sshpass

      - name: Check container status by docker command
        run: docker ps -a

      - name: Update SSH known host
        run: |
          mkdir -p $HOME/.ssh
          chmod 700 $HOME/.ssh
          touch $HOME/.ssh/known_hosts
          chmod 600 $HOME/.ssh/known_hosts
          ssh-keygen -R [127.0.0.1]:8022 -f $HOME/.ssh/known_hosts
          ssh-keyscan -t rsa -p 8022 127.0.0.1 >> $HOME/.ssh/known_hosts
          ssh-keygen -H -f $HOME/.ssh/known_hosts

      - name: Check container status by executing shell command in container
        run: ./nebula_dev_shell.sh echo "hello"
